apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base
patchesStrategicMerge:
- service-patch.yaml
replicas:
- count: 5
  name: angular-app
# Surcharge de l'image
images:
- name: angular-app-prod
  newName: stevymonkam/angular-app-prod
  newTag: 51-prod
- name: stevymonkam/front5
  newName: stevymonkam/angular-app-prod
  newTag: 42-prod
